kind: Deployment
apiVersion: apps/v1
metadata:
  name: etlflow-test
  namespace: dev
  labels:
    app: etlflow-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etlflow-test
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /etlflow/metrics
        prometheus.io/port: "8080"
        git_commit_hash: gsha_abc1234
      labels:
        app: etlflow-test
    spec:
      volumes:
        - name: etlflow-test
          secret:
            secretName: etlflow-test
      containers:
        - name: etlflow-test
          image: etlflow-examples
          imagePullPolicy: Always
          env:
            - name: PROPERTIES_FILE_PATH
              value: /opt/docker/conf/loaddata.properties
            - name: LOG_DB_URL
              value: 'jdbc:postgresql://postgres:5432/etlflow'
            - name: LOG_DB_USER
              value: etlflow
            - name: LOG_DB_PWD
              value: etlflow
            - name: LOG_DB_DRIVER
              value: org.postgresql.Driver
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: etlflow-test
                  key: sa-creds
          resources:
            limits:
              cpu: "2"
              memory: "3Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort : 8080
          volumeMounts:
            - name: etlflow-test
              mountPath: /opt/docker/conf/cred.json
              subPath: cred.json